# Generated by Django 5.1.1 on 2024-10-03 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='password',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
